In [2]:
import pandas as pd

# 1. CSV 파일 불러오기
# (공공데이터는 보통 'cp949' 또는 'euc-kr' 인코딩을 사용합니다. 에러 발생 시 'utf-8'로 변경하세요.)
file_path = 'gangwon_filtered.csv'
df = pd.read_csv(file_path)

# 2. '도로명주소' 열에서 '강원'이 포함된 행 필터링 (결측치 예방 na=False)
# filtered_df = df[df['도로명주소'].str.contains('강원특별자치도 춘천시', na=False)]
filtered_df = df[df['영업상태명'].str.contains('영업/정상', na=False)]

# 3. 필터링된 결과 확인
print(f"전체 데이터 수: {len(df)}건")
print(f"강원 지역 데이터 수: {len(filtered_df)}건")

# 4. 필터링 결과 저장 (엑셀에서 바로 열 때 깨지지 않도록 utf-8-sig 사용)
filtered_df.to_csv('gangwon_filtered.csv', index=False, encoding='utf-8-sig')

전체 데이터 수: 4793건
강원 지역 데이터 수: 4793건

In [2]:
uptae_list = filtered_df['업태구분명'].dropna().drop_duplicates().tolist()
print(uptae_list)
uptae_list.to_csv('title.csv', index=False, encoding='utf-8-sig')

['기타', '호프/통닭', '한식', '분식', '정종/대포집/소주방', '경양식', '식육(숯불구이)', '푸드트럭', '탕류(보신용)', '일식', '횟집', '중국식', '통닭(치킨)', '외국음식전문점(인도,태국등)', '까페', '감성주점', '라이브카페', '뷔페식', '김밥(도시락)', '패스트푸드', '키즈카페', '전통찻집', '복어취급', '냉면집', '패밀리레스트랑']

AttributeError: 'list' object has no attribute 'to_csv'

In [3]:
gita_df = filtered_df[filtered_df['업태구분명'] == "기타"]
print(f"'기타' 업태 데이터 수: {len(gita_df)}건")
print(gita_df)

'기타' 업태 데이터 수: 933건
      개방자치단체코드                    관리번호       인허가일자  영업상태명  폐업일자   소재지면적  \
0      4181000  4181000-101-2026-00182  2026-06-16  영업/정상   NaN   87.24
2      4181000  4181000-101-2026-00195  2026-06-19  영업/정상   NaN   34.65
6      4181000  4181000-101-2026-00167  2026-06-01  영업/정상   NaN   32.00
16     4181000  4181000-101-2026-00095  2026-04-15  영업/정상   NaN   22.36
27     4181000  4181000-101-2026-00144  2026-05-20  영업/정상   NaN   60.64
...        ...                     ...         ...    ...   ...     ...
4746   4181000  4181000-101-2013-00202  2013-07-29  영업/정상   NaN  115.42
4760   4181000  4181000-101-2015-00377  2015-12-21  영업/정상   NaN  141.60
4762   4181000  4181000-101-2015-00378  2015-12-21  영업/정상   NaN   83.36
4766   4181000  4181000-101-2016-00302  2016-09-20  영업/정상   NaN  163.80
4770   4181000  4181000-101-2019-00260  2019-09-25  영업/정상   NaN   52.87

      소재지우편번호  도로명우편번호                 사업장명 업태구분명  ... 월세액  위생업태명  전통업소주된음식  \
0         NaN  24336.0                하프앤로프    기타  ... NaN     기타       NaN
2         NaN  24394.0                  여름밭    기타  ... NaN     기타       NaN
6         NaN  24273.0                  낙원별    기타  ... NaN     기타       NaN
16        NaN  24409.0         춘천안식원장례식장(주)    기타  ... NaN     기타       NaN
27        NaN  24295.0             코끼리카페춘천점    기타  ... NaN     기타       NaN
...       ...      ...                  ...   ...  ...  ..    ...       ...
4746      NaN  24405.0  고니아커피(GONIA COFFEE)    기타  ... NaN     기타       NaN
4760      NaN  24292.0           그래도좋아회(본점)    기타  ... NaN     기타       NaN
4762      NaN  24209.0                어반스트릿    기타  ... NaN     기타       NaN
4766      NaN  24219.0       투썸플레이스춘천사농점(2)    기타  ... NaN     기타       NaN
4770      NaN  24274.0                 녹색시간    기타  ... NaN     기타       NaN

      전통업소지정번호         전화번호        좌표정보(X)        좌표정보(Y)  \
0          NaN          NaN  264210.667586  485781.254390
2          NaN          NaN  265712.496238  483786.902128
6          NaN          NaN  263841.485470  486598.734319
16         NaN  332624119.0  265473.483047  473225.648511
27         NaN          NaN  265070.949567  486048.906340
...        ...          ...            ...            ...
4746       NaN  332620708.0  266238.366076  483643.402167
4760       NaN  332558242.0  265231.993818  486555.923938
4762       NaN  332523555.0  266189.645356  488135.981981
4766       NaN  332420807.0  263448.811965  490382.097711
4770       NaN          NaN  263759.576184  486591.959840

                             지번주소 홈페이지               최종수정시점
0          강원특별자치도 춘천시 효자동 464-4   NaN  2026-06-16 11:37:10
2          강원특별자치도 춘천시 석사동 827-4   NaN  2026-06-19 13:39:13
6         강원특별자치도 춘천시 중앙로2가 88-1   NaN  2026-06-01 10:50:09
16     강원특별자치도 춘천시 동산면 군자리 703-5   NaN  2026-04-15 10:26:15
27        강원특별자치도 춘천시 효자동 615-12   NaN  2026-05-20 14:12:30
...                           ...  ...                  ...
4746  강원특별자치도 춘천시 동내면 거두리 954-16   NaN  2025-11-11 09:22:03
4760      강원특별자치도 춘천시 후평동 678-15   NaN  2024-09-19 13:17:58
4762     강원특별자치도 춘천시 동면 장학리 1001   NaN  2021-12-19 20:31:24
4766         강원특별자치도 춘천시 사농동 365   NaN  2020-03-11 11:23:35
4770        강원특별자치도 춘천시 낙원동 60-4   NaN  2019-09-25 17:23:11

[933 rows x 39 columns]

In [4]:
result_df = gita_df[['업태구분명', '사업장명', '지번주소']]
print(result_df)
result_df.to_csv('other.csv', index=False, encoding='utf-8-sig')

     업태구분명                 사업장명                         지번주소
0       기타                하프앤로프       강원특별자치도 춘천시 효자동 464-4
2       기타                  여름밭       강원특별자치도 춘천시 석사동 827-4
6       기타                  낙원별      강원특별자치도 춘천시 중앙로2가 88-1
16      기타         춘천안식원장례식장(주)   강원특별자치도 춘천시 동산면 군자리 703-5
27      기타             코끼리카페춘천점      강원특별자치도 춘천시 효자동 615-12
...    ...                  ...                          ...
4746    기타  고니아커피(GONIA COFFEE)  강원특별자치도 춘천시 동내면 거두리 954-16
4760    기타           그래도좋아회(본점)      강원특별자치도 춘천시 후평동 678-15
4762    기타                어반스트릿     강원특별자치도 춘천시 동면 장학리 1001
4766    기타       투썸플레이스춘천사농점(2)         강원특별자치도 춘천시 사농동 365
4770    기타                 녹색시간        강원특별자치도 춘천시 낙원동 60-4

[933 rows x 3 columns]

In [1]:
import pandas as pd

sssss = 'gangwon_filtered.csv'
df = pd.read_csv(sssss)

exclude_list = [
    "정종/대포집/소주방",
    "푸드트럭",
    "감성주점",
    "패스트푸드",
    "키즈카페",
    "패밀리레스트랑",
    "외국음식전문점(인도,태국등)"
]

result_df = df[['업태구분명', '사업장명', '지번주소']]
filtered_df = result_df[~result_df['업태구분명'].isin(exclude_list)]

print(filtered_df.head())
filtered_df.to_csv('filter_file.csv', index=False, encoding='utf-8-sig')

   업태구분명        사업장명                    지번주소
0     기타       하프앤로프  강원특별자치도 춘천시 효자동 464-4
1  호프/통닭  처갓집양념치킨퇴계점  강원특별자치도 춘천시 퇴계동 914-4
2     기타         여름밭  강원특별자치도 춘천시 석사동 827-4
3     한식  원유통슈퍼키친춘천점   강원특별자치도 춘천시 우두동 1089
4     한식       숙이네국밥  강원특별자치도 춘천시 칠전동 590-4

In [3]:
import time

In [2]:
API_KEY = "AIzaSyBpntbMN0VUcZ31FeIp7I9RhAyWLS4wk84"

In [4]:
import requests



address = "강원특별자치도 춘천시 교동 135-13"

response = requests.get(
    "https://maps.googleapis.com/maps/api/geocode/json",
    params={
        "address": address,
        "key": API_KEY,
        "language": "ko",
        "region": "kr"
    },
    timeout=20
)

data = response.json()

print("상태:", data["status"])

if data["status"] == "OK":
    result = data["results"][0]
    location = result["geometry"]["location"]

    print("입력 주소:", address)
    print("변환 주소:", result["formatted_address"])
    print("위도:", location["lat"])
    print("경도:", location["lng"])
    print("정확도:", result["geometry"]["location_type"])
    print("Place ID:", result["place_id"])
else:
    print("오류:", data.get("error_message"))

상태: OK
입력 주소: 강원특별자치도 춘천시 교동 135-13
변환 주소: 대한민국 강원특별자치도 춘천시 교동 135-13
위도: 37.877686
경도: 127.7356878
정확도: ROOFTOP
Place ID: ChIJd9zrv8TlYjURT14IaIcDOU0

[1/70] 처리 오류: 강원특별자치도 춘천시 교동 135-13 → Invalid value '37.877686' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[1/70] 빌즈버거 → 처리 오류: Invalid value '37.877686' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[2/70] 처리 오류: 강원특별자치도 춘천시 교동 156-23 → Invalid value '37.8829089' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[2/70] 명백집춘천점 → 처리 오류: Invalid value '37.8829089' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[3/70] 처리 오류: 강원특별자치도 춘천시 교동 156-23 → Invalid value '37.8829089' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[3/70] 한림양장 → 처리 오류: Invalid value '37.8829089' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[4/70] 처리 오류: 강원특별자치도 춘천시 교동 156-4 → Invalid value '37.8827784' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[4/70] 포차천국 → 처리 오류: Invalid value '37.8827784' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[5/70] 처리 오류: 강원특별자치도 춘천시 교동 136-7 → Invalid value '37.8814458' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[5/70] 대박소주방 → 처리 오류: Invalid value '37.8814458' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[6/70] 처리 오류: 강원특별자치도 춘천시 교동 15-3 → Invalid value '37.8832839' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[6/70] 우영야식 → 처리 오류: Invalid value '37.8832839' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[7/70] 처리 오류: 강원특별자치도 춘천시 교동 154-1 → Invalid value '37.8832887' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[7/70] 낙지락지 → 처리 오류: Invalid value '37.8832887' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[8/70] 처리 오류: 강원특별자치도 춘천시 교동 135-1 → Invalid value '37.877917' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[8/70] 우영갈비 → 처리 오류: Invalid value '37.877917' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[9/70] 처리 오류: 강원특별자치도 춘천시 교동 55-8 → Invalid value '37.8814025' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[9/70] 육면 → 처리 오류: Invalid value '37.8814025' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[10/70] 처리 오류: 강원특별자치도 춘천시 교동 11-14 → Invalid value '37.88258709999999' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[10/70] 꼴두바우 → 처리 오류: Invalid value '37.88258709999999' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[11/70] 처리 오류: 강원특별자치도 춘천시 교동 156-8 → Invalid value '37.8824122' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[11/70] 푸릉 → 처리 오류: Invalid value '37.8824122' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[12/70] 처리 오류: 강원특별자치도 춘천시 교동 93-177 → Invalid value '37.883409' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[12/70] 바게트하우스 → 처리 오류: Invalid value '37.883409' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[13/70] 처리 오류: 강원특별자치도 춘천시 교동 156-1 → Invalid value '37.8831468' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[13/70] 메가푸드 → 처리 오류: Invalid value '37.8831468' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[14/70] 처리 오류: 강원특별자치도 춘천시 교동 149-8 → Invalid value '37.8822664' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[14/70] 반올림피자샵춘천1호점 → 처리 오류: Invalid value '37.8822664' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[15/70] 처리 오류: 강원특별자치도 춘천시 교동 156-16 → Invalid value '37.8834057' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[15/70] 송가네냉면주는알밥집 → 처리 오류: Invalid value '37.8834057' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[16/70] 처리 오류: 강원특별자치도 춘천시 교동 152-3 → Invalid value '37.8835841' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[16/70] 도쿄라멘춘천한림대점 → 처리 오류: Invalid value '37.8835841' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[17/70] 처리 오류: 강원특별자치도 춘천시 교동 160-6 → Invalid value '37.8814903' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[17/70] 네네치킨(교동후평점) → 처리 오류: Invalid value '37.8814903' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[18/70] 처리 오류: 강원특별자치도 춘천시 교동 150-8 → Invalid value '37.8826064' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[18/70] 돼학로 → 처리 오류: Invalid value '37.8826064' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[19/70] 처리 오류: 강원특별자치도 춘천시 교동 156-3 → Invalid value '37.8830325' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[19/70] 한림골 → 처리 오류: Invalid value '37.8830325' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[20/70] 처리 오류: 강원특별자치도 춘천시 교동 11-1 → Invalid value '37.883218' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[20/70] 부자네토종순대국 → 처리 오류: Invalid value '37.883218' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[21/70] 처리 오류: 강원특별자치도 춘천시 교동 18-2 → Invalid value '37.882832' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[21/70] 화양객잔 → 처리 오류: Invalid value '37.882832' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[22/70] 처리 오류: 강원특별자치도 춘천시 교동 150-6 → Invalid value '37.8824401' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[22/70] 페이크러버스 → 처리 오류: Invalid value '37.8824401' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[23/70] 처리 오류: 강원특별자치도 춘천시 교동 152-1 → Invalid value '37.8836032' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[23/70] 동신 냉삼집 → 처리 오류: Invalid value '37.8836032' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[24/70] 처리 오류: 강원특별자치도 춘천시 교동 152-7 → Invalid value '37.8836607' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[24/70] 풀잎 → 처리 오류: Invalid value '37.8836607' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[25/70] 처리 오류: 강원특별자치도 춘천시 교동 158-1 → Invalid value '37.883323' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[25/70] 한솥도시락한림대앞점 → 처리 오류: Invalid value '37.883323' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[26/70] 처리 오류: 강원특별자치도 춘천시 교동 86-7 → Invalid value '37.8810101' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[26/70] 옛촌 → 처리 오류: Invalid value '37.8810101' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[27/70] 처리 오류: 강원특별자치도 춘천시 교동 85-2 → Invalid value '37.8805919' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[27/70] 블루핀 → 처리 오류: Invalid value '37.8805919' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[28/70] 처리 오류: 강원특별자치도 춘천시 교동 148-4 → Invalid value '37.8816318' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[28/70] 그라시아 → 처리 오류: Invalid value '37.8816318' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[29/70] 처리 오류: 강원특별자치도 춘천시 교동 93-193 → Invalid value '37.88327719999999' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[29/70] 클라로 → 처리 오류: Invalid value '37.88327719999999' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[30/70] 처리 오류: 강원특별자치도 춘천시 교동 162-1 → Invalid value '37.8817406' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[30/70] 야키토리무명 → 처리 오류: Invalid value '37.8817406' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[31/70] 처리 오류: 강원특별자치도 춘천시 교동 157-13 → Invalid value '37.8827504' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[31/70] 미가락 → 처리 오류: Invalid value '37.8827504' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[32/70] 처리 오류: 강원특별자치도 춘천시 교동 137-2 → Invalid value '37.881432' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[32/70] 배고파 → 처리 오류: Invalid value '37.881432' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[33/70] 처리 오류: 강원특별자치도 춘천시 교동 149-12 → Invalid value '37.8822226' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[33/70] 오야 → 처리 오류: Invalid value '37.8822226' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[34/70] 처리 오류: 강원특별자치도 춘천시 교동 156-6 → Invalid value '37.8825473' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[34/70] 성심로11-1 → 처리 오류: Invalid value '37.8825473' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[35/70] 처리 오류: 강원특별자치도 춘천시 교동 152-3 152-2,152-8(1층) → Invalid value '37.8835841' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[35/70] 토마토도시락춘천한림대점 → 처리 오류: Invalid value '37.8835841' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[36/70] 처리 오류: 강원특별자치도 춘천시 교동 156-5 → Invalid value '37.8826671' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[36/70] 도스마스한림대점 → 처리 오류: Invalid value '37.8826671' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[37/70] 처리 오류: 강원특별자치도 춘천시 교동 93-155 → Invalid value '37.8853373' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[37/70] 가람스넥 → 처리 오류: Invalid value '37.8853373' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[38/70] 처리 오류: 강원특별자치도 춘천시 교동 113-47 → Invalid value '37.8799579' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[38/70] 오늘산책 → 처리 오류: Invalid value '37.8799579' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[39/70] 처리 오류: 강원특별자치도 춘천시 교동 156-2 외1필지 → Invalid value '37.8831533' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[39/70] 투썸플레이스한림대점 → 처리 오류: Invalid value '37.8831533' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[40/70] 처리 오류: 강원특별자치도 춘천시 교동 156-23 → Invalid value '37.8829089' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[40/70] 구마족발한림대점 → 처리 오류: Invalid value '37.8829089' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[41/70] 처리 오류: 강원특별자치도 춘천시 교동 152-1 (지하1층) → Invalid value '37.8836032' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[41/70] 엄마손식당 → 처리 오류: Invalid value '37.8836032' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[42/70] 처리 오류: 강원특별자치도 춘천시 교동 156-5 → Invalid value '37.8826671' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[42/70] 성심로11 → 처리 오류: Invalid value '37.8826671' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[43/70] 처리 오류: 강원특별자치도 춘천시 교동 136-13 → Invalid value '37.8819285' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[43/70] 본가김밥 → 처리 오류: Invalid value '37.8819285' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[44/70] 처리 오류: 강원특별자치도 춘천시 교동 157-17 → Invalid value '37.8829256' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[44/70] 향리원 마라탕 → 처리 오류: Invalid value '37.8829256' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[45/70] 처리 오류: 강원특별자치도 춘천시 교동 146-12 → Invalid value '37.8812586' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[45/70] 상린 → 처리 오류: Invalid value '37.8812586' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[46/70] 처리 오류: 강원특별자치도 춘천시 교동 136-7 → Invalid value '37.8814458' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[46/70] 분식집에하숙하는붕어빵 → 처리 오류: Invalid value '37.8814458' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[47/70] 처리 오류: 강원특별자치도 춘천시 교동 158-21 → Invalid value '37.8832419' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[47/70] 존버당 → 처리 오류: Invalid value '37.8832419' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[48/70] 처리 오류: 강원특별자치도 춘천시 교동 4-20 → Invalid value '37.883205' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[48/70] 할머니순대국 → 처리 오류: Invalid value '37.883205' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[49/70] 처리 오류: 강원특별자치도 춘천시 교동 157-26 → Invalid value '37.8831203' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[49/70] 맘스터치한림대점 → 처리 오류: Invalid value '37.8831203' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[50/70] 처리 오류: 강원특별자치도 춘천시 교동 16-27 → Invalid value '37.882922' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[50/70] 미성카츠 → 처리 오류: Invalid value '37.882922' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[51/70] 처리 오류: 강원특별자치도 춘천시 교동 157-15 → Invalid value '37.8833508' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[51/70] 화산마라탕 → 처리 오류: Invalid value '37.8833508' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[52/70] 처리 오류: 강원특별자치도 춘천시 교동 157-16 1층 → Invalid value '37.8825353' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[52/70] 한림광장 → 처리 오류: Invalid value '37.8825353' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[53/70] 처리 오류: 강원특별자치도 춘천시 교동 112-14 1층 → Invalid value '37.8797836' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[53/70] 치맥한잔 → 처리 오류: Invalid value '37.8797836' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[54/70] 처리 오류: 강원특별자치도 춘천시 교동 15-3 → Invalid value '37.8832839' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[54/70] 와플칸 한림대점 → 처리 오류: Invalid value '37.8832839' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[55/70] 처리 오류: 강원특별자치도 춘천시 교동 93-95 → Invalid value '37.8832065' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[55/70] 책방달방 → 처리 오류: Invalid value '37.8832065' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[56/70] 처리 오류: 강원특별자치도 춘천시 교동 152-5 → Invalid value '37.8836141' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[56/70] 피자스쿨춘천한림대점 → 처리 오류: Invalid value '37.8836141' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[57/70] 처리 오류: 강원특별자치도 춘천시 교동 152-1 → Invalid value '37.8836032' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[57/70] 대암감자탕한림대점 → 처리 오류: Invalid value '37.8836032' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[58/70] 처리 오류: 강원특별자치도 춘천시 교동 136-12 → Invalid value '37.8818404' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[58/70] 라이키 → 처리 오류: Invalid value '37.8818404' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[59/70] 처리 오류: 강원특별자치도 춘천시 교동 164-5 → Invalid value '37.8807921' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[59/70] 파닭에파무쳐(춘천1호점) → 처리 오류: Invalid value '37.8807921' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[60/70] 처리 오류: 강원특별자치도 춘천시 교동 126-18 → Invalid value '37.8782257' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[60/70] 소확행피자춘천광장점 → 처리 오류: Invalid value '37.8782257' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[61/70] 처리 오류: 강원특별자치도 춘천시 교동 152-7 → Invalid value '37.8836607' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[61/70] 별채식당 → 처리 오류: Invalid value '37.8836607' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[62/70] 처리 오류: 강원특별자치도 춘천시 교동 156-27 → Invalid value '37.8834234' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[62/70] 고바우부대찌개 → 처리 오류: Invalid value '37.8834234' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[63/70] 처리 오류: 강원특별자치도 춘천시 교동 157-25 → Invalid value '37.8832269' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[63/70] 오필승닭발한림대점 → 처리 오류: Invalid value '37.8832269' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[64/70] 처리 오류: 강원특별자치도 춘천시 교동 117-1 (1층) → Invalid value '37.8812066' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[64/70] 룡의부활 → 처리 오류: Invalid value '37.8812066' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[65/70] 처리 오류: 강원특별자치도 춘천시 교동 93-157 → Invalid value '37.8852155' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[65/70] 고향스넥 → 처리 오류: Invalid value '37.8852155' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[66/70] 처리 오류: 강원특별자치도 춘천시 교동 137-1 → Invalid value '37.8815445' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[66/70] 딜리버리프렌즈 → 처리 오류: Invalid value '37.8815445' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[67/70] 처리 오류: 강원특별자치도 춘천시 교동 156-1 → Invalid value '37.8831468' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[67/70] 딜리버리춘천점 → 처리 오류: Invalid value '37.8831468' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[68/70] 처리 오류: 강원특별자치도 춘천시 교동 93-28 → Invalid value '37.8833267' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[68/70] 진스키친 → 처리 오류: Invalid value '37.8833267' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[69/70] 처리 오류: 강원특별자치도 춘천시 교동 154 → Invalid value '37.8834389' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[69/70] 아바이순대국 → 처리 오류: Invalid value '37.8834389' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[70/70] 처리 오류: 강원특별자치도 춘천시 교동 156-28 → Invalid value '37.8833055' for dtype 'str'. Value should be a string or missing value, got 'float' instead.
[70/70] 진주밥상 → 처리 오류: Invalid value '37.8833055' for dtype 'str'. Value should be a string or missing value, got 'float' instead.

지오코딩 완료
지오코딩상태
처리 오류: Invalid value '37.8829089' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           3
처리 오류: Invalid value '37.8836032' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           3
처리 오류: Invalid value '37.8814458' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           2

,업태구분명,사업장명,지번주소,위도,경도,변환주소,좌표정확도,place_id,지오코딩상태
0,기타,빌즈버거,강원특별자치도 춘천시 교동 135-13,NaN,NaN,NaN,NaN,NaN,처리 오류: Invalid value '37.877686' for dtype 'st...
1,한식,명백집춘천점,강원특별자치도 춘천시 교동 156-23,NaN,NaN,NaN,NaN,NaN,처리 오류: Invalid value '37.8829089' for dtype 's...
2,한식,한림양장,강원특별자치도 춘천시 교동 156-23,NaN,NaN,NaN,NaN,NaN,처리 오류: Invalid value '37.8829089' for dtype 's...
3,통닭(치킨),포차천국,강원특별자치도 춘천시 교동 156-4,NaN,NaN,NaN,NaN,NaN,처리 오류: Invalid value '37.8827784' for dtype 's...
4,호프/통닭,대박소주방,강원특별자치도 춘천시 교동 136-7,NaN,NaN,NaN,NaN,NaN,처리 오류: Invalid value '37.8814458' for dtype 's...

지오코딩상태
처리 오류: Invalid value '37.8829089' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           3
처리 오류: Invalid value '37.8836032' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           3
처리 오류: Invalid value '37.8814458' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           2
처리 오류: Invalid value '37.8832839' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           2
처리 오류: Invalid value '37.8831468' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           2
처리 오류: Invalid value '37.8835841' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           2
처리 오류: Invalid value '37.8836607' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           2
처리 오류: Invalid value '37.8826671' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           2
처리 오류: Invalid value '37.877686' for dtype 'str'. Value should be a string or missing value, got 'float' instead.            1
처리 오류: Invalid value '37.8827784' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8832887' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.877917' for dtype 'str'. Value should be a string or missing value, got 'float' instead.            1
처리 오류: Invalid value '37.8814025' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.88258709999999' for dtype 'str'. Value should be a string or missing value, got 'float' instead.    1
처리 오류: Invalid value '37.8824122' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.883409' for dtype 'str'. Value should be a string or missing value, got 'float' instead.            1
처리 오류: Invalid value '37.8822664' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8834057' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8814903' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8826064' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8830325' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.883218' for dtype 'str'. Value should be a string or missing value, got 'float' instead.            1
처리 오류: Invalid value '37.882832' for dtype 'str'. Value should be a string or missing value, got 'float' instead.            1
처리 오류: Invalid value '37.8824401' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.883323' for dtype 'str'. Value should be a string or missing value, got 'float' instead.            1
처리 오류: Invalid value '37.8810101' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8805919' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8816318' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.88327719999999' for dtype 'str'. Value should be a string or missing value, got 'float' instead.    1
처리 오류: Invalid value '37.8817406' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8827504' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.881432' for dtype 'str'. Value should be a string or missing value, got 'float' instead.            1
처리 오류: Invalid value '37.8822226' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8825473' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8853373' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8799579' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8831533' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8819285' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8829256' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8812586' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8832419' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.883205' for dtype 'str'. Value should be a string or missing value, got 'float' instead.            1
처리 오류: Invalid value '37.8831203' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.882922' for dtype 'str'. Value should be a string or missing value, got 'float' instead.            1
처리 오류: Invalid value '37.8833508' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8825353' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8797836' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8832065' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8836141' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8818404' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8807921' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8782257' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8834234' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8832269' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8812066' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8852155' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8815445' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8833267' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8834389' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
처리 오류: Invalid value '37.8833055' for dtype 'str'. Value should be a string or missing value, got 'float' instead.           1
Name: count, dtype: int64
Series([], Name: count, dtype: int64)

NameError: name '__file__' is not defined

In [6]:
# 교동 음식점 지오코딩: ArcGIS 방식
import time
import pandas as pd
import requests

INPUT_FILE = "filter_file_Gyo_dong.csv"
OUTPUT_FILE = "filter_file_Gyo_dong_geocoded.csv"

df = pd.read_csv(INPUT_FILE, encoding="utf-8-sig")

# 좌표 열은 반드시 숫자형으로 생성
df["위도"] = pd.Series(float("nan"), index=df.index, dtype="float64")
df["경도"] = pd.Series(float("nan"), index=df.index, dtype="float64")
df["변환주소"] = pd.Series(pd.NA, index=df.index, dtype="string")
df["지오코딩상태"] = pd.Series(pd.NA, index=df.index, dtype="string")
df["매칭점수"] = pd.Series(float("nan"), index=df.index, dtype="float64")

API_URL = (
    "https://geocode.arcgis.com/arcgis/rest/services/"
    "World/GeocodeServer/findAddressCandidates"
)

session = requests.Session()
session.headers["User-Agent"] = "Mozilla/5.0 restaurant-list-geocoder/1.0"

# 같은 주소를 중복 조회하지 않기 위한 캐시
cache = {}

for number, index in enumerate(df.index, start=1):
    address = " ".join(str(df.at[index, "지번주소"]).strip().split())

    if not address or address.lower() == "nan":
        result = {"상태": "주소없음"}

    elif address in cache:
        result = cache[address]

    else:
        try:
            response = session.get(
                API_URL,
                params={
                    "SingleLine": address,
                    "f": "json",
                    "maxLocations": 1,
                    "outFields": "Match_addr",
                    "countryCode": "KOR",
                    "forStorage": "false",
                    "outSR": 4326,
                },
                timeout=30,
            )
            response.raise_for_status()
            data = response.json()

            if data.get("error"):
                message = data["error"].get("message", "ArcGIS API 오류")
                result = {"상태": f"API오류: {message}"}

            else:
                candidates = data.get("candidates", [])

                if candidates:
                    candidate = candidates[0]
                    location = candidate["location"]
                    score = float(candidate.get("score", 0))

                    result = {
                        "상태": "성공",
                        "위도": float(location["y"]),
                        "경도": float(location["x"]),
                        "변환주소": candidate.get("address", ""),
                        "매칭점수": score,
                    }
                else:
                    result = {"상태": "검색결과없음"}

        except requests.RequestException as error:
            result = {"상태": f"요청오류: {error}"}
        except (KeyError, TypeError, ValueError) as error:
            result = {"상태": f"응답처리오류: {error}"}

        cache[address] = result
        time.sleep(0.25)

    df.at[index, "지오코딩상태"] = result["상태"]

    if result["상태"] == "성공":
        df.at[index, "위도"] = result["위도"]
        df.at[index, "경도"] = result["경도"]
        df.at[index, "변환주소"] = result["변환주소"]
        df.at[index, "매칭점수"] = result["매칭점수"]

    print(
        f"[{number}/{len(df)}] "
        f"{address} -> {result['상태']}"
    )

    # 실행 중단에 대비한 중간 저장
    if number % 10 == 0:
        df.to_csv(
            OUTPUT_FILE,
            index=False,
            encoding="utf-8-sig",
        )

df.to_csv(
    OUTPUT_FILE,
    index=False,
    encoding="utf-8-sig",
)

print("\n지오코딩 완료")
print(df["지오코딩상태"].value_counts(dropna=False))
print("결과 파일:", OUTPUT_FILE)

display(
    df[
        [
            "사업장명",
            "지번주소",
            "위도",
            "경도",
            "변환주소",
            "매칭점수",
            "지오코딩상태",
        ]
    ].head(10)
)

[1/70] 강원특별자치도 춘천시 교동 135-13 -> 성공
[2/70] 강원특별자치도 춘천시 교동 156-23 -> 성공
[3/70] 강원특별자치도 춘천시 교동 156-23 -> 성공
[4/70] 강원특별자치도 춘천시 교동 156-4 -> 성공
[5/70] 강원특별자치도 춘천시 교동 136-7 -> 성공
[6/70] 강원특별자치도 춘천시 교동 15-3 -> 성공
[7/70] 강원특별자치도 춘천시 교동 154-1 -> 성공
[8/70] 강원특별자치도 춘천시 교동 135-1 -> 성공
[9/70] 강원특별자치도 춘천시 교동 55-8 -> 성공
[10/70] 강원특별자치도 춘천시 교동 11-14 -> 성공
[11/70] 강원특별자치도 춘천시 교동 156-8 -> 성공
[12/70] 강원특별자치도 춘천시 교동 93-177 -> 성공
[13/70] 강원특별자치도 춘천시 교동 156-1 -> 성공
[14/70] 강원특별자치도 춘천시 교동 149-8 -> 성공
[15/70] 강원특별자치도 춘천시 교동 156-16 -> 성공
[16/70] 강원특별자치도 춘천시 교동 152-3 -> 성공
[17/70] 강원특별자치도 춘천시 교동 160-6 -> 성공
[18/70] 강원특별자치도 춘천시 교동 150-8 -> 성공
[19/70] 강원특별자치도 춘천시 교동 156-3 -> 성공
[20/70] 강원특별자치도 춘천시 교동 11-1 -> 성공
[21/70] 강원특별자치도 춘천시 교동 18-2 -> 성공
[22/70] 강원특별자치도 춘천시 교동 150-6 -> 성공
[23/70] 강원특별자치도 춘천시 교동 152-1 -> 성공
[24/70] 강원특별자치도 춘천시 교동 152-7 -> 성공
[25/70] 강원특별자치도 춘천시 교동 158-1 -> 성공
[26/70] 강원특별자치도 춘천시 교동 86-7 -> 성공
[27/70] 강원특별자치도 춘천시 교동 85-2 -> 성공
[28/70] 강원특별자치도 춘천시 교동 148-4 -> 성공
[29/70] 강원특별자치도 춘천시 교동 93-193 -> 성공
[30/70] 강원특별자치도 춘천시 교동 162-1 -> 성공
[31/70] 강원특별자치도 춘천시 교동 157-13 -> 성공
[32/70] 강원특별자치도 춘천시 교동 137-2 -> 성공
[33/70] 강원특별자치도 춘천시 교동 149-12 -> 성공
[34/70] 강원특별자치도 춘천시 교동 156-6 -> 성공
[35/70] 강원특별자치도 춘천시 교동 152-3 152-2,152-8(1층) -> 성공
[36/70] 강원특별자치도 춘천시 교동 156-5 -> 성공
[37/70] 강원특별자치도 춘천시 교동 93-155 -> 성공
[38/70] 강원특별자치도 춘천시 교동 113-47 -> 성공
[39/70] 강원특별자치도 춘천시 교동 156-2 외1필지 -> 성공
[40/70] 강원특별자치도 춘천시 교동 156-23 -> 성공
[41/70] 강원특별자치도 춘천시 교동 152-1 (지하1층) -> 성공
[42/70] 강원특별자치도 춘천시 교동 156-5 -> 성공
[43/70] 강원특별자치도 춘천시 교동 136-13 -> 성공
[44/70] 강원특별자치도 춘천시 교동 157-17 -> 성공
[45/70] 강원특별자치도 춘천시 교동 146-12 -> 성공
[46/70] 강원특별자치도 춘천시 교동 136-7 -> 성공
[47/70] 강원특별자치도 춘천시 교동 158-21 -> 성공
[48/70] 강원특별자치도 춘천시 교동 4-20 -> 성공
[49/70] 강원특별자치도 춘천시 교동 157-26 -> 성공
[50/70] 강원특별자치도 춘천시 교동 16-27 -> 성공
[51/70] 강원특별자치도 춘천시 교동 157-15 -> 성공
[52/70] 강원특별자치도 춘천시 교동 157-16 1층 -> 성공
[53/70] 강원특별자치도 춘천시 교동 112-14 1층 -> 성공
[54/70] 강원특별자치도 춘천시 교동 15-3 -> 성공
[55/70] 강원특별자치도 춘천시 교동 93-95 -> 성공
[56/70] 강원특별자치도 춘천시 교동 152-5 -> 성공
[57/70] 강원특별자치도 춘천시 교동 152-1 -> 성공
[58/70] 강원특별자치도 춘천시 교동 136-12 -> 성공
[59/70] 강원특별자치도 춘천시 교동 164-5 -> 성공
[60/70] 강원특별자치도 춘천시 교동 126-18 -> 성공
[61/70] 강원특별자치도 춘천시 교동 152-7 -> 성공
[62/70] 강원특별자치도 춘천시 교동 156-27 -> 성공
[63/70] 강원특별자치도 춘천시 교동 157-25 -> 성공
[64/70] 강원특별자치도 춘천시 교동 117-1 (1층) -> 성공
[65/70] 강원특별자치도 춘천시 교동 93-157 -> 성공
[66/70] 강원특별자치도 춘천시 교동 137-1 -> 성공
[67/70] 강원특별자치도 춘천시 교동 156-1 -> 성공
[68/70] 강원특별자치도 춘천시 교동 93-28 -> 성공
[69/70] 강원특별자치도 춘천시 교동 154 -> 성공
[70/70] 강원특별자치도 춘천시 교동 156-28 -> 성공

지오코딩 완료
지오코딩상태
성공    70
Name: count, dtype: int64[pyarrow]
결과 파일: filter_file_Gyo_dong_geocoded.csv

,사업장명,지번주소,위도,경도,변환주소,매칭점수,지오코딩상태
0,빌즈버거,강원특별자치도 춘천시 교동 135-13,37.877686,127.735688,강원특별자치도 춘천시 교동 135-13,100.0,성공
1,명백집춘천점,강원특별자치도 춘천시 교동 156-23,37.882909,127.739596,강원특별자치도 춘천시 교동 156-23,100.0,성공
2,한림양장,강원특별자치도 춘천시 교동 156-23,37.882909,127.739596,강원특별자치도 춘천시 교동 156-23,100.0,성공
3,포차천국,강원특별자치도 춘천시 교동 156-4,37.882779,127.739605,강원특별자치도 춘천시 교동 156-4,100.0,성공
4,대박소주방,강원특별자치도 춘천시 교동 136-7,37.881446,127.734513,강원특별자치도 춘천시 교동 136-7,100.0,성공
5,우영야식,강원특별자치도 춘천시 교동 15-3,37.883284,127.737936,강원특별자치도 춘천시 교동 15-3,100.0,성공
6,낙지락지,강원특별자치도 춘천시 교동 154-1,37.883289,127.739961,강원특별자치도 춘천시 교동 154-1,100.0,성공
7,우영갈비,강원특별자치도 춘천시 교동 135-1,37.877917,127.735627,강원특별자치도 춘천시 교동 135-1,100.0,성공
8,육면,강원특별자치도 춘천시 교동 55-8,37.881403,127.732951,강원특별자치도 춘천시 교동 55-8,100.0,성공
9,꼴두바우,강원특별자치도 춘천시 교동 11-14,37.882588,127.737196,강원특별자치도 춘천시 교동 11-14,100.0,성공

In [ ]:
import time
import pandas as pd
import requests
# 정렬 방식 재정의 파일